spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ets-ww
    username: sa
    password: test
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
     dialect: org.hibernate.dialect.SQLServer2017Dialect
     ddl-auto: create-drop
ebean:
  packages: com.swire.etsww.domain
  ddl:
    generate: false
    run: false
  migration:
    run: false
  debug:
    sql: true
    lazyload: false
    logging:
      logfilesharing: all
      directory: logs
      iud: sql
      query: sql
      sqlquery: sql
      txnCommit: none
  mappingLocations: classpath:/ebean-xml-mappings
server:
  servlet:
    context-path: /ets-ww
  port: 8080

swagger:
  enabled: true
  package: com.swire.etsww.controller

wechat:
  cp:
    corpId: ww135e9a631a5e7d2d
    appConfigs:
      - agentId: 1000002
        secret: kfuZUeNkA4FZdUrbXS0nM2tjOlvEGRQ5gLe1Pd6ThGc
      #        token: 111
      #        aesKey: 111
      - agentId: 1000003
        secret: o06elzdnxNxTy_ubhVYRxdsOPbZsLK2qic6OyKMsbAA
#        token: 111
#        aesKey: 111